const userInterests = {
  INTEREST_1: 'INTEREST_1',
  INTEREST_2: 'INTEREST_2',
  INTEREST_3: 'INTEREST_3',
  INTEREST_4: 'INTEREST_4',
  INTEREST_5: 'INTEREST_5',
  INTEREST_6: 'INTEREST_6',
  INTEREST_7: 'INTEREST_7',
  INTEREST_8: 'INTEREST_8',
  INTEREST_9: 'INTEREST_9',
  INTEREST_10: 'INTEREST_10',
  INTEREST_11: 'INTEREST_11',
  INTEREST_12: 'INTEREST_12',
  INTEREST_13: 'INTEREST_13',
  INTEREST_14: 'INTEREST_14',
  INTEREST_15: 'INTEREST_15',
  INTEREST_16: 'INTEREST_16',
  INTEREST_17: 'INTEREST_17',
  INTEREST_18: 'INTEREST_18',
  INTEREST_19: 'INTEREST_19',
  INTEREST_20: 'INTEREST_20',
};

module.exports = userInterests;
